# Generated by Django 4.2.23 on 2025-08-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='kullanicilar',
        ),
        migrations.AlterModelTable(
            name='userlog',
            table='kullanici_loglari',
        ),
    ]
