# Generated by Django 4.2.23 on 2025-08-21 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_type',
            field=models.CharField(choices=[('login', 'Giriş Yapıldı'), ('logout', 'Çıkış Yapıldı'), ('login_failed', 'Başarısız Giriş'), ('password_change', 'Şifre Değiştirildi'), ('profile_update', 'Profil Güncellendi'), ('user_created', 'Kullanıcı Oluşturuldu'), ('user_updated', 'Kullanıcı Güncellendi'), ('user_deleted', 'Kullanıcı Silindi'), ('device_add', 'Cihaz Eklendi'), ('device_edit', 'Cihaz Düzenlendi'), ('device_delete', 'Cihaz Silindi'), ('permission_update', 'Yetki Güncellendi'), ('account_locked', 'Hesap Kilitlendi'), ('account_unlocked', 'Hesap Açıldı'), ('bulk_action', 'Toplu İşlem'), ('export_data', 'Veri Dışa Aktarıldı'), ('system_access', 'Sistem Erişimi'), ('admin_action', 'Admin İşlemi')], max_length=50, verbose_name='Log Türü'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
