# Generated by Django 4.2.23 on 2025-08-21 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userlog_log_type_alter_userlog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('device_add', 'Cihaz Ekle'), ('device_list', 'Cihaz Listesi'), ('user_add', 'Kullanıcı Ekle'), ('user_list', 'Kullanıcı Listesi'), ('statistics', 'İstatistikler'), ('activity_log', 'Aktivite Logları'), ('system_info', 'Sistem Bilgileri'), ('admin_panel', 'Yönetim Paneli'), ('profile', 'Profil'), ('change_password', 'Şifre Değiştir'), ('export_csv', 'CSV Export'), ('export_json', 'JSON Export'), ('bulk_actions', 'Toplu İşlemler'), ('permissions', 'Yetki Yönetimi')], max_length=50, verbose_name='İşlem')),
                ('display_name', models.CharField(max_length=100, verbose_name='Görünen Ad')),
                ('icon', models.CharField(default='fas fa-star', max_length=50, verbose_name='İkon')),
                ('color', models.CharField(default='cyan', max_length=20, verbose_name='Renk')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Hızlı İşlem',
                'verbose_name_plural': 'Hızlı İşlemler',
                'db_table': 'hizli_islemler',
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'action')},
            },
        ),
    ]
