# Generated by Django 5.2.5 on 2025-08-20 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm_number', models.CharField(help_text='Örnek: +905551234567 veya 05551234567', max_length=15, validators=[django.core.validators.RegexValidator(message='Geçerli bir telefon numarası giriniz.', regex='^\\+?[0-9]{10,15}$')], verbose_name='GSM Numarası')),
                ('device_email', models.EmailField(help_text='Cihaza özel e-posta adresi', max_length=254, unique=True, verbose_name='Cihaz E-posta Adresi')),
                ('device_type', models.CharField(choices=[('phone', 'Telefon'), ('tablet', 'Tablet'), ('computer', 'Bilgisayar'), ('iot', 'IoT Cihazı'), ('other', 'Diğer')], default='phone', max_length=20, verbose_name='Cihaz Cinsi')),
                ('device_name', models.CharField(blank=True, help_text='Cihaza özel isim (örn: İş Telefonu)', max_length=100, null=True, verbose_name='Cihaz Adı')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model')),
                ('imei', models.CharField(blank=True, help_text='15 haneli IMEI numarası', max_length=15, null=True, verbose_name='IMEI Numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cihaz Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('notes', models.TextField(blank=True, help_text='Cihaz hakkında ek bilgiler', null=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
