# Generated by Django 4.2.23 on 2025-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('phone', 'Telefon'), ('tablet', 'Tablet'), ('computer', 'Bilgisayar'), ('iot', 'IoT Cihazı'), ('vehicle_camera', 'Araç Kamerası'), ('vehicle_tracker', 'Araç Takip Cihazı'), ('ip_camera', 'IP Kamera'), ('other', 'Diğer')], default='phone', max_length=20, verbose_name='Cihaz Cinsi'),
        ),
    ]
