# Generated by Django 4.2.23 on 2025-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_group',
            field=models.CharField(blank=True, help_text='Cihazın ait olduğu grup veya birim', max_length=100, null=True, verbose_name='Cihaz Birliği'),
        ),
    ]
