# Generated by Django 5.2.5 on 2025-08-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_device_device_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="email_number",
            field=models.CharField(
                blank=True,
                help_text="E-posta için özel numara (örn: 001, 002)",
                max_length=20,
                null=True,
                verbose_name="E-posta No",
            ),
        ),
    ]
