# Generated by Django 5.2.5 on 2025-08-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_device_email_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="email_number",
            field=models.CharField(
                blank=True,
                help_text="15 haneli cihaz e-mail numarası",
                max_length=15,
                null=True,
                verbose_name="Cihaz E-mail No",
            ),
        ),
    ]
